name: kpi-bots

on:
  workflow_dispatch:
  schedule:
    # JSTで毎日9時と21時に実行(UTCで0時と12時)
    - cron: "0 0,12 * * *"

jobs:
  run:
    name: notify::kpi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 14.19.0
      - name: Upgrade npm
        run: npm i -g npm@8.3.1
      - name: Install Dependencies
        run: npm ci
      - name: Run
        run: npm run notify::kpi
        env:
          MAINNET_RPC: ${{secrets.MAINNET_RPC}}
          SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
          UPPER_THRESHOLD_PRICE: ${{secrets.UPPER_THRESHOLD_PRICE}}
          LOWER_THRESHOLD_PRICE: ${{secrets.LOWER_THRESHOLD_PRICE}}
